server:
  port: 8081
  error:
    include-stacktrace: never

spring:
  application:
    name: api
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://dpg-cp8kqj5ds78s73c5msi0-a.virginia-postgres.render.com:5432/vollmed}
    username: ${DATASOURCE_USERNAME:vollmed}
    password: ${DATASOURCE_PASSWORD:iYvaf8UXUm6LSldES6OlU6gs9MCmwvX3}
    #postgres://dpg-cp8kqj5ds78s73c5msi0-a.virginia-postgres.render.com/vollmed
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  # defer-datasource-initialization: true
  sql:
    init:
      mode: always
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
jwt:
  public:
    key: ${JTW_PUBLIC:classpath:keys/app.pub}
  private:
    key: ${JTW_PRIVATE:classpath:keys/app.key}